name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: qqiao/dev-env:latest
      options: --user root

    steps:
      - uses: actions/checkout@v2
      - run: chmod -R 777 .
      - run: yarn install
      - run: yarn test
